#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v10
# autospec commit: 5905be97e829
#
# Source0 file verified with key 0x78A1B4DFE8F9C57E (rousseau@debian.org)
#
Name     : ccid
Version  : 1.5.5
Release  : 13
URL      : https://ccid.apdu.fr/files/ccid-1.5.5.tar.bz2
Source0  : https://ccid.apdu.fr/files/ccid-1.5.5.tar.bz2
Source1  : https://ccid.apdu.fr/files/ccid-1.5.5.tar.bz2.asc
Source2  : 78A1B4DFE8F9C57E.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: ccid-config = %{version}-%{release}
Requires: ccid-lib = %{version}-%{release}
Requires: ccid-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : flex
BuildRequires : gnupg
BuildRequires : pkgconfig(libpcsclite)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(zlib)
BuildRequires : systemd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The files buffer.[c|h], checksum.c and proto-t1.c comes from the OpenCT
project <http://www.opensc.org/>

%package config
Summary: config components for the ccid package.
Group: Default

%description config
config components for the ccid package.


%package lib
Summary: lib components for the ccid package.
Group: Libraries
Requires: ccid-license = %{version}-%{release}

%description lib
lib components for the ccid package.


%package license
Summary: license components for the ccid package.
Group: Default

%description license
license components for the ccid package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 78A1B4DFE8F9C57E' gpg.status
%setup -q -n ccid-1.5.5
cd %{_builddir}/ccid-1.5.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1715198217
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1715198217
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ccid
cp %{_builddir}/ccid-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ccid/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
cp %{_builddir}/ccid-%{version}/src/openct/LICENSE %{buildroot}/usr/share/package-licenses/ccid/f25c7f6146e4ac975b9e0c4fb3936a9af04d437a || :
cp %{_builddir}/ccid-%{version}/src/towitoko/COPYING %{buildroot}/usr/share/package-licenses/ccid/207a4f23aeb278d4d863854e3d3787247da1ca43 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
## install_append content
mkdir -p %{buildroot}/usr/lib/udev/rules.d/
cp src/92_pcscd_ccid.rules %{buildroot}/usr/lib/udev/rules.d/
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/92_pcscd_ccid.rules

%files lib
%defattr(-,root,root,-)
/usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ccid/207a4f23aeb278d4d863854e3d3787247da1ca43
/usr/share/package-licenses/ccid/9a1929f4700d2407c70b507b3b2aaf6226a9543c
/usr/share/package-licenses/ccid/f25c7f6146e4ac975b9e0c4fb3936a9af04d437a
